INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700');
INSERT INTO `products`(`SKU`, `Name`, `Price`, `Attribute`) VALUES ('JVC200123','Acme DISC','1','700')